<?php include_once 'Views/Layouts/menu-admin.phtml'; ?>
<?php
if(isset($_GET['id']))
{
	?>
		<h2>Modifier <?php echo $profile->getData('firstname').' '.$profile->getData('lastname'); ?></h2>
	<?php
}
else
{
	?>
		<h2>Création d'un nouvel utilisateur</h2>
	<?php
}
?>
<form action="" method="post">
  	<div class="form-group">
		<label for="firstname">Prénom</label>
		<input type="text" class="form-control" value="<?php echo $profile->getData('firstname'); ?>" name="firstname" id="firstname" placeholder="Prénom">
	</div>
	<div class="form-group">
		<label for="lastname">Nom</label>
		<input type="text" class="form-control" value="<?php echo $profile->getData('lastname'); ?>" name="lastname" id="lastname" placeholder="Nom">
	</div>
	<div class="form-group">
		<label for="email">Adresse Email</label>
		<input type="email" class="form-control" value="<?php echo $profile->getData('email'); ?>" name="email" id="email" placeholder="Adresse Email">
	</div>
	<div class="form-group">
		<label for="phone">Téléphone</label>
		<input type="text" class="form-control" value="<?php echo $profile->getData('phone'); ?>" name="phone" id="phone" placeholder="Telephone">
	</div>
	<div class="form-group">
		<label for="password">Mot de passe</label>
		<input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
		<label for="password2">Répétez le mot de passe</label>
		<input type="password" class="form-control" id="password2" name="password2" placeholder="Répétez le mot de passe">
	</div>
	<?php 
	if(App::profile()->isAdmin())
	{
		?>
			<div class="form-group">
				<label for="role_id">Niveau de permissions</label>
				<select class="form-control" name="role_id" id="role_id">
					<?php
						foreach($roles as $role)
						{
							?>
								<option value="<?php echo $role->getData('id'); ?>" <?php echo App::profile()->getData('role_id') == $role->getData('id') ? 'selected': ''; ?>><?php echo $role->getData('name'); ?></option>
							<?php
						}
					?>
				</select>
			</div>
		<?php
	}
	?>
  <button type="submit" class="btn btn-success"><?php echo isset($_GET['id']) ? 'Modifier':'Créer'; ?></button>
</form>