<?php include_once 'Views/Layouts/menu-trainer.phtml'; ?>
<h2>Modifier la compétence <?php echo $level->getMatter()->getData('title') ?> de <?php echo $level->getTrainer()->getData('name') ?></h2>

<form method="post" action="#" enctype="multipart/form-data">
	<div class="form-group">
		<label for="note">Note</label>
		<input type="text" name="note" id="note" note="<?php echo $level->getData('note'); ?>" readonly value="<?php echo $level->getData('note') ?>" style="border:0; font-weight:bold;">
		<div id="slider-range-max"></div>
	</div>
	<div class="form-group">
		<label for="appreciation">Appreciation</label>
		<input id="appreciation" type="text" name="appreciation" value="<?php echo $level->getData('appreciation') ?>">
	</div>
	
	<input type="submit" value="Enregistrer.">
	
</form>

<a href="/index.php?c=Trainer&a=addEditMatters&id=<?php echo $level->getTrainer()->getData('id'); ?>">Retour</a>
