<?php include_once 'Views/Layouts/menu-trainer.phtml'; ?>

<div id="form-ajax"></div>
<div id="results-ajax">
	<table class="table table-striped table-bordered" id="matters-levels">
		<tr>
			<td>Matière</td>
			<td>Note</td>
			<td>Appréciation</td>
			<td></td>
		</tr>
		<?php
		if($trainer->getLevels())
		{
			foreach($trainer->getLevels() as $level)
			{ 
				?>
					<tr>
						<td><?php echo $level->getMatter()->getData('title'); ?></td>
						<td><?php echo $level->getData('note'); ?></td>
						<td><?php echo $level->getData('appreciation'); ?></td>
						<td>
							<a class="btn btn-primary edit-level" data-id="<?php echo $level->id; ?>" href="#">Editer</a>
						</td>
						<td>
							<form method="post">
								<input type="hidden" name="level" value="<?php echo $level->getData('id'); ?>">
								<input type="hidden" name="delete" value="1">
								<input type="submit" class="btn btn-danger" value="Supprimer">
							</form>
						</td>
					</tr>
				<?php
			}			
		}
		?>
	</table>
</div>
<br><br>
<button class="btn btn-success" id="add-level">Ajouter une matière</button>
<form style="display:none;" method="post" action="" enctype="multipart/form-data" id="add-level-form">
	<label for="matter_id">Matière</label>
	<select class="form-control" name="matter_id" id="matter_id">
		<?php
			foreach ($matters as $matter)
			{ 
				?>
					<option value="<?php echo $matter->getData('id') ?>">
						<?php
							echo $matter->getData('title');
						?>
					</option>
				<?php
			}
		?>
	</select>
	<input type="submit" class="btn btn-success form-control" value="Ajouter">
</form>
<script>
$(document).ready(function(){
	$(document).on('click', '#add-level', function(){
		$('#add-level-form').toggle();
	});
	$(document).on('click', '.edit-level', function(e){
		e.preventDefault();
		$.ajax({
		  method: "POST",
		  url: "index.php?c=ajax&a=editLevelForm",
		  data: { id: $(this).attr('data-id') }
		})
		.done(function( html ) {
			$('#form-ajax').html(html);
		});
	})
	$(document).on('submit', '#edit-level-form', function(e){
		e.preventDefault();
		$.ajax({
		  method: "POST",
		  url: "index.php?c=ajax&a=editLevel",
		  data: $(this).serialize()
		})
		.done(function( html ) {
			$('#results-ajax').html(html);
			$('#form-ajax').empty();
		});
	});
});
</script>