<h2>Liste des formateurs</h2>
<table class="table table-striped table-bordered">
	<tr>
		<td>ID</td>
		<td>Prénom</td>
		<td>Nom</td>
		<td>Portable</td>
		<td>Email</td>
		<td>Sexe</td>
		<td>Niveau d'étude</td>
		<td>Externe</td>
		<td>Taux horaire</td>
		<td>Informations Complémentaires</td>
	</tr>
	<?php
		if($trainers)
		{
			foreach($trainers as $trainer)
			{
				?>
					<tr>
						<td>
							<?= $trainer->getData('id'); ?>		
						</td>
						<td>
							<?= $trainer->getData('firstname'); ?>
						</td>
						<td>
							<?= $trainer->getData('name'); ?>
						</td>
						<td>
							<?= $trainer->getData('cellphone'); ?>
						</td>
						<td>
							<?= $trainer->getData('mail'); ?>
						</td>
						<td>
							<?= $trainer->getData('gender'); ?>
						</td>
						<td>
							<?= $trainer->getData('study_levels_id'); ?>
						</td>
						<td>
							<?= $trainer->getData('trainer_extern'); ?>
						</td>
						<td>
							<?= $trainer->getData('hourly_rate'); ?>
						</td>
						<td>
							<?= $trainer->getData('further_informations'); ?>
						</td>
						<td>
							<a href="index.php?c=Trainer&a=addEdit&id=<?= $trainer->getData("id"); ?>" class="btn btn-primary">Modifier</a>
						</td>
						<td>
							<a href="index.php?c=Trainer&a=show&id=<?= $trainer->getData("id"); ?>" class="btn btn-primary">Afficher</a>
						</td>
						<td>
							<form method="post">
								<input type="hidden" name="trainer" value="<?= $trainer->getData('id'); ?>">
								<input type="hidden" name="delete" value="1">
								<input type="submit" class="btn btn-primary" value="Supprimer">
							</form>
						</td>
					</tr>
				<?php
			}
		}
	?>
</table>
<a class="btn btn-success" href="index.php?c=Trainer&a=addEdit">Ajouter un formateur</a>