<?php include_once 'Views/Layouts/menu-trainer.phtml'; ?>
<div id="form-ajax"></div>
<table class="table table-striped table-bordered">
	<tr>
		<td>Session de Formation</td>
		<td>Date de début</td>
		<td>Date de fin</td>
		<td>Total heures</td>
		<td></td>
	</tr>
	<?php
		if($trainer->getParticipations())
		{
			foreach($trainer->getParticipations() as $participation)
			{
				?>
					<tr>
						<td>
							<?php echo $participation->getFormationSession()->getFormation()->getData('title').' du '.date('d/m/y', strtotime($participation->getFormationSession()->getData('begin_date'))).' au '.date('d/m/y', strtotime($participation->getFormationSession()->getData('ending_date'))); ?>
						</td>
						<td><?php echo date("d/m/Y", strtotime($participation->date_start)); ?></td>
						<td><?php echo date("d/m/Y", strtotime($participation->date_end)); ?></td>
						<td><?php echo $participation->getData('total_hours'); ?></td>
						<td>
							<a class="btn btn-primary manage-interventionheets mis-<?= $participation->id ?>" data-id="<?= $participation->id ?>">Gestion des feuilles d'intervention</a>
							<form method="post">
								<input type="hidden" name="participation_id" value="<?php echo $participation->getData('id'); ?>">
								<input type="hidden" name="delete" value="1">
								<input type="submit" value="Supprimer" class="btn btn-danger">
							</form>
						</td>
					</tr>
				<?php
			}
		}
	?>
</table>
<h2>Ajouter une participation de <strong><?= $trainer->getFullName(); ?></strong> à une session de formation</h2>

<form method="post" action="#" enctype="multipart/form-data" class="form-horizontal">
	<div class="form-group">
		<label for="month" class="col-sm-2 control-label">Date début</label>
		<div class="col-sm-10">	
			<input type="text" class="form-control datepicker" name="date_start">
		</div>
	</div>
	<div class="form-group">
		<label for="month" class="col-sm-2 control-label">Date de fin</label>
		<div class="col-sm-10">	
			<input type="text" class="form-control datepicker" name="date_end">
		</div>
	</div>
	<div class="form-group">
		<label for="total_hours" class="col-sm-2 control-label">Total heures</label>
		<div class="col-sm-10">
			<input type="text" name="total_hours" id="total_hours" data-validation="number" data-validation="required" class="form-control">
		</div>
	</div>

	<div class="form-group">
		<label for="formation_session" class="col-sm-2 control-label">Session de formation</label>
		<div class="col-sm-10">
			<select name="formation_session_id" id="formation_session" class="form-control">
				<?php
					foreach($formationSessions as $formationSession)
					{ 
						?>
							<option value="<?php echo $formationSession->getData('id') ?>">
								<?php
									echo $formationSession->getFormation()->getData('title').' du '.date('d/m/y', strtotime($formationSession->getData('begin_date'))).' au '.date('d/m/y', strtotime($formationSession->getData('ending_date')));
								?>
							</option>
						<?php
					}
				?>
			</select>
		</div>
	</div>
	<input type="submit" value="Ajouter" class="btn btn-success col-sm-offset-2 col-sm-3">

</form>
<script>
$(document).ready(function(){
	$(document).on('click', '#add-interventionsheet', function(){
		$('#add-interventionsheet-form').toggle();
	});
	$(document).on('click', '.delete-interventionsheet', function(e){
		e.preventDefault();
		var that = this;
		$.ajax({
		  method: "POST",
		  url: "index.php?c=ajax&a=deleteInterventionsheet",
		  data: { id: $(this).attr('data-id') }
		})
		.done(function( html ) {
			$(that).parent('td').parent('tr').remove();
		});
	});
	$(document).on('click', '.manage-interventionheets', function(e){
		e.preventDefault();
		$.ajax({
		  method: "POST",
		  url: "index.php?c=ajax&a=interventionsheet",
		  data: { id: $(this).attr('data-id') }
		})
		.done(function( html ) {
			$('#form-ajax').html(html);
		});
	});
	$(document).on('submit', '#add-interventionsheet-form', function(e){
		var that = this;
		e.preventDefault();
		$.ajax({
		  method: "POST",
		  url: "index.php?c=ajax&a=addInterventionsheetForm",
		  data: $(this).serialize()
		})
		.done(function( html ) {
			$('.mis-'+$(that).attr('data-id')).click();
		});
	});
});
</script>