<?php include_once 'Views/Layouts/breadcrumbs.phtml'; ?>
<?= addBreadcrumbs(['Formateurs' => 'index.php?c=trainer&a=list', $trainer->getFullName() => 'index.php?c=trainer&a=show&id='.$_GET['id'], 'Feuilles de présence & Sessions de formation' => '']); ?>
<?php include_once 'Views/Layouts/menu-trainer.phtml'; ?>
<h2>Feuilles de présence de <?php echo $trainer->getData('firstname').' '.$trainer->getData('name'); ?></h2>

<table class="table table-striped table-bordered">
	<tr>
		<td>Session de Formation</td>
		<td>Mois</td>
		<td>Année</td>
		<td>Total heures</td>
	</tr>
	<?php
		if($trainer->getTimesheets())
		{
			foreach($trainer->getTimesheets() as $timesheet)
			{
				?>
					<tr>
						<td>
							<?php echo $timesheet->getFormationSession()->getFormation()->getData('title').' du '.date('d/m/y', strtotime($timesheet->getFormationSession()->getData('begin_date'))).' au '.date('d/m/y', strtotime($timesheet->getFormationSession()->getData('ending_date'))); ?>
						</td>
						<td><?php echo strftime("%B", strtotime(date('F', mktime(0, 0, 0, $timesheet->getData('month'), 10)))); ?></td>
						<td><?php echo $timesheet->getData('year'); ?></td>
						<td><?php echo $timesheet->getData('total_hours'); ?></td>
						<td>
							<form method="post">
								<input type="hidden" name="timesheet_id" value="<?php echo $timesheet->getData('id'); ?>">
								<input type="hidden" name="delete" value="1">
								<input type="submit" value="Supprimer" class="btn btn-danger">
							</form>
						</td>
					</tr>
				<?php
			}
		}
	?>
</table>
<h2>Ajouter feuille de présence</h2>

<form method="post" action="#" enctype="multipart/form-data" class="form-horizontal">
	<div class="form-group">
		<label for="month" class="col-sm-2 control-label">Mois</label>
		<div class="col-sm-10">	
			<select name="month" id="month" class="form-control">
				<option value="1">Janvier</option>
				<option value="2">Février</option>
				<option value="3">Mars</option>
				<option value="4">Avril</option>
				<option value="5">Mai</option>
				<option value="6">Juin</option>
				<option value="7">Juillet</option>
				<option value="8">Août</option>
				<option value="9">Septembre</option>
				<option value="10">Octobre</option>
				<option value="11">Novembre</option>
				<option value="12">Décembre</option>
			</select>
		</div>
	</div>

	<div class="form-group">
		<label for="year" class="col-sm-2 control-label">Année</label>
		<div class="col-sm-10">
			<select name="year" id="year" class="form-control">
				<?php
					for ($y=2000; $y <= 2100; $y++) 
					{ 
						if (date("Y") == $y)
						{
							?><option value="<?php echo $y ?>" selected><?php echo $y; ?></option><?php
						}
						else
						{
							?><option value="<?php echo $y ?>"><?php echo $y; ?></option><?php
						}
					}
				?>
			</select>
		</div>
	</div>

	<div class="form-group">
		<label for="total_hours" class="col-sm-2 control-label">Total heures</label>
		<div class="col-sm-10">
			<input type="text" name="total_hours" id="total_hours" data-validation="number" data-validation="required" class="form-control">
		</div>
	</div>

	<div class="form-group">
		<label for="formation_session" class="col-sm-2 control-label">Session de formation</label>
		<div class="col-sm-10">
			<select name="formation_session_id" id="formation_session" class="form-control">
				<?php
					foreach($formationSessions as $formationSession)
					{ 
						?>
							<option value="<?php echo $formationSession->getData('id') ?>">
								<?php
									echo $formationSession->getFormation()->getData('title').' du '.date('d/m/y', strtotime($formationSession->getData('begin_date'))).' au '.date('d/m/y', strtotime($formationSession->getData('ending_date')));
								?>
							</option>
						<?php
					}
				?>
			</select>
		</div>
	</div>
	<input type="submit" value="Ajouter" class="btn btn-success col-sm-offset-2 col-sm-3">

</form>