CREATE TABLE matter
(
	id SERIAL PRIMARY KEY,
	intitule VARCHAR
);

ALTER TABLE trainer 
ADD COLUMN id SERIAL PRIMARY KEY,
ADD COLUMN create_date DATE,
ADD COLUMN update_date DATE,
ADD COLUMN create_uid INT,
ADD COLUMN update_uid INT,
ADD COLUMN active BOOLEAN;

ALTER TABLE timesheet 
ADD COLUMN id SERIAL PRIMARY KEY,
ADD COLUMN create_date DATE,
ADD COLUMN update_date DATE,
ADD COLUMN create_uid INT,
ADD COLUMN update_uid INT,
ADD COLUMN active BOOLEAN;