<?php

$breadcrumbs = array();
$breadcrumbs['editLevel'] = 'addEditMatters';
$breadcrumbs['addEditMatters'] = 'list';
$breadcrumbs['timesheet'] = 'list';
$breadcrumbs['addEdit'] = 'list';
$breadcrumbs['list'] = null;

$breadcrumb = $_GET['a'];
for($i = 0; $breadcrumb != null; $i++)
{
	echo $breadcrumb.' > ';
	$breadcrumb = $breadcrumbs[$breadcrumb];
}

breadcrumbs(['home' => 'index.php', 'formateurs' => 'formateurs.php', 'liste' => 'liste.php']);

function addBreadcrumbs($array)
{
	$url = 'Accueil -> ';
	foreach( $array as $key => $value )
	{
		$url .= '<a href="' . $value . '">' . $key  . ' -> ';
	}
	return $url;
} ?>

<?= breadcrumbs(['users' => 'index.php?c=users&a=list']); ?>