<?php

function addBreadcrumbs($array)
{
	$url = '<div class="container-fluid"><ol class="breadcrumb">';
	$url .= '<li><a href="/">Accueil</a></li>';
	$count = 1;
	foreach( $array as $key => $value )
	{
		if($count == sizeof($array)) // si on est au dernier element du tableau
		{
			$url .= '<li class="active">'.$key.'</li>';
		}
		else
		{
			$url .= '<li><a href="' . $value . '">' . $key  . '</a></li>';
		}
		$count++;
	}
	$url .= '</ol></div>';
	return $url;
} ?>

