</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="./Design/js/form-validator/jquery.form-validator.min.js"></script>
<script src="./Design/js/form-validator/lang/fr.js"></script>
<script src="./Design/js/form-validator/location.js"></script>
<script src="./Design/js/autoComplete/jquery.autocomplete.js"></script>
<script src="./Design/js/script.js"></script>
</body>
</html>