<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/cosmo/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" href="/Design/css/jquery.auto-complete.css">
		<link rel="stylesheet" href="/Design/css/main.css">
		<script>(function(w,d,u){w.readyQ=[];w.bindReadyQ=[];function p(x,y){if(x=="ready"){w.bindReadyQ.push(y);}else{w.readyQ.push(x);}};var a={ready:p,bind:p};w.$=w.jQuery=function(f){if(f===d||f===u){return a}else{p(f)}}})(window,document)</script>

	</head>
	<body>
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index.php"><i class="fa fa-keyboard-o"></i> Gestion des Formations</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == '' ? 'active' : '') ?>"><a href="index.php"><i class="fa fa-home"></i> Accueil</a></li>
					<li class="divider-vertical"></li>
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == 'trainee' ? 'active' : '') ?>"><a href="index.php?c=trainee"><i class="fa fa-users"></i> Etudiants</a></li>
					<li class="divider-vertical"></li>
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == 'formation' ? 'active' : '') ?>"><a href="index.php?c=formation"><i class="fa fa-graduation-cap"></i> Formations</a></li>
					<li class="divider-vertical"></li>
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == 'trainer' ? 'active' : '') ?>"><a href="index.php?c=trainer"><i class="fa fa-male"></i> Formateurs</a></li>
					<li class="divider-vertical"></li>
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == 'company' ? 'active' : '') ?>"><a href="index.php?c=company"><i class="fa fa-building-o"></i> Entreprises</a></li>
					<li class="divider-vertical"></li>
					<li class="<?= (isset($_GET['c']) && $_GET['c'] == 'internship' ? 'active' : '') ?>"><a href="index.php?c=internship"><i class="fa fa-laptop"></i> Stages</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
							<i class="fa fa-user"></i> Administrateur	<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li><a href="#"><i class="fa fa-wrench"></i> Mes paramètres</a></li>
							<li class="divider"></li>
							<li><a href="#"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container" style="padding-top: 60px;">