<div class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.php"><i class="fa fa-keyboard-o"></i> Gestion des Formations</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="index.php"><i class="fa fa-home"></i> Accueil</a></li>
				<li class="divider-vertical"></li>
				<li><a href="<?= url('trainees'); ?>"><i class="fa fa-users"></i> Etudiants</a></li>
				<li class="divider-vertical"></li>
				<li><a href="<?= url('formations'); ?>"><i class="fa fa-graduation-cap"></i> Formations</a></li>
				<li class="divider-vertical"></li>
				<li><a href="<?= url('companies'); ?>"><i class="fa fa-male"></i> Formateurs</a></li>
				<li class="divider-vertical"></li>
				<li><a href="<?= url('companies'); ?>"><i class="fa fa-building-o"></i> Entreprises</a></li>
				<li class="divider-vertical"></li>
				<li><a href="<?= url('internships'); ?>"><i class="fa fa-laptop"></i> Stages</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user"></i> Administrateur	<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#"><i class="fa fa-wrench"></i> Mes paramètres</a></li>
						<li class="divider"></li>
						<li><a href="#"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</div>

<div class="container" style="padding-top: 70px;">