<h3><?php echo $trainer->getFullName(); ?></h3>
<ul class="nav nav-tabs">
	<li role="presentation" <?php echo ($_GET['a'] == 'addEdit' ? 'class="active"' : '') ?>>
		<a href="<?php echo url('/index.php?c=Trainer&a=addEdit&id='); ?><?php echo $trainer->getData("id"); ?>">
			Modifier le formateur
		</a>
	</li>
	<li role="presentation" <?php echo ($_GET['a'] == 'timesheet' ? 'class="active"' : '') ?>>
		<a href="<?php echo url('/index.php?c=Trainer&a=timesheet&id='); ?><?php echo $trainer->getData("id"); ?>">
			Feuilles de présence & Sessions de formation
		</a>
	</li>
	<li role="presentation" <?php echo (($_GET['a'] == 'addEditMatters' || $_GET['a'] == 'editLevel') ? 'class="active"' : '') ?>>
		<a href="<?php echo url('/index.php?c=Trainer&a=addEditMatters&id='); ?><?php echo $trainer->getData("id"); ?>">
			Niveaux & Compétences
		</a>
	</li>
</ul>