<div class="page-header">
	<h1><i class="fa fa-male"></i> Gestion des formateurs <small><i class="fa fa-angle-double-right"></i> <?= $title; ?></small></h1>
</div>
<ul class="nav nav-tabs">
	<?php 
    if(Profile::allowed(1))
    {
        ?>
		<li role="presentation" <?php echo ($_GET['a'] == 'addEdit' ? 'class="active"' : '') ?>>
			<a href="/index.php?c=Trainer&a=addEdit&id=<?php echo $trainer->getData('id'); ?>">
				Ajouter / Modifier le formateur
			</a>
		</li>
		<li role="presentation" <?php echo ($_GET['a'] == 'participation' ? 'class="active"' : '') ?>>
			<a href="/index.php?c=Trainer&a=participation&id=<?php echo $trainer->getData('id'); ?>">
				Participation aux Sessions de formation
			</a>
		</li>
		<li role="presentation" <?php echo (($_GET['a'] == 'addEditMatters' || $_GET['a'] == 'editLevel') ? 'class="active"' : '') ?>>
			<a href="/index.php?c=Trainer&a=addEditMatters&id=<?php echo $trainer->getData('id'); ?>">
				Niveaux & Compétences
			</a>
		</li>
		<?php
	} ?>
</ul>