<?php
/*
<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped">
            <thead>
            <tr>
                <th class="text-center">ID</th>
                <th class="text-center">Nom</th>
                <th class="text-center">Ville</th>
                <th class="text-center">Pays</th>
                <th class="text-center">Rajout</th>
                <th class="text-center">Stages</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach( $items as $item ): ?>
                <tr>
                    <td class="text-center"><?= $item->id; ?></td>
                    <td class="text-center"><a href="<?= url('companies/' . $item->id); ?>"><?= $item->name; ?></a></td>
                    <td class="text-center"><?= $item->city; ?></td>
                    <td class="text-center"><?= $item->country; ?></td>
                    <td class="text-center"><?= \Core\Helpers\Date::ago($item->create_date); ?></td>
                    <td class="text-center"><?= \Core\Helpers\String::strPlural('stage', $item->countInternships($item->id)); ?>
                    </td>
                    <td class="text-center">
                        <a href="<?= url('companies/' . $item->id . '/edit') ?>" class="btn btn-success btn-sm"><i class="fa fa-pencil"></i> Modifier</a>
                        <a href="<?= url('companies/' . $item->id . '/delete') ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i> Supprimer</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
 */
?>
<div class="form-group">
    <select name="truc" class="form-control">
        <?php foreach( $items as $item ): ?>
        <option value="<?= $item->id; ?>"><?= $item->name; ?></option>
        <?php endforeach; ?>
    </select>
</div>





