<div class="panel panel-default">
    <div class="panel-heading text-center">
        Modifier la compétence "<?php echo $level->getMatter()->getData('title') ?>" de <?php echo $level->getTrainer()->getFullName(); ?>
    </div>
    <div class="panel-body">
        <form method="post" action="#" enctype="multipart/form-data" id="edit-level-form" data-id="<?php echo $level->id; ?>" data-model-name="Level">
            <div class="form-group">
                <label for="note">Note</label>
                <input type="text" name="note" id="note" note="<?php echo $level->getData('note'); ?>" readonly value="<?php echo $level->getData('note') ?>" class="form-control">
                <div id="slider-range-max"></div>
            </div>
            <div class="form-group">
                <label for="appreciation">Appreciation</label>
                <input id="appreciation" type="text" name="appreciation" value="<?php echo $level->getData('appreciation') ?>" class="form-control">
            </div>
            <input type="hidden" name="id" value="<?php echo $level->id; ?>">
            <input type="submit" value="Enregistrer" class="btn btn-success">
        </form>
    </div>
</div>