<div class ="col-md-3">
    <form method="post" action="#" class="post-add-matter">
        <input type="hidden" name="formation" value="<?= $id_formation; ?>">
        <select name="matter" class="form-control select-<?= $id_formation; ?>">
            <?php
            for ($i=0; $i < count($coll_matter); $i++):

                $notRefpedago = true;
                for ($j=0; $j < count($coll_refpedago); $j++)
                {
                    if( $coll_refpedago[$j]->getData('matters_id') == $coll_matter[$i]->getData('id') )
                    {
                        $notRefpedago = false;
                    }
                }

                if( $notRefpedago ): ?>
                    <option class="option-<?= $coll_matter[$i]->getData('id'); ?>" value="<?= $coll_matter[$i]->getData('id'); ?>"><?= $coll_matter[$i]->getData('title'); ?></option>
                <?php endif;

            endfor; ?>
        </select>
        <button name="submit">Ajouter cette matière</button>
    </form>
</div>