<div class="page-header">
    <h1>Se connecter</h1>
</div>

<?= viewFile('partials.flash'); ?>
<?= viewFile('partials.errors'); ?>

<form action="<?= url('login'); ?>" method="post" class="form-vertical">
    <?= $form->text('email', 'Votre adresse email'); ?>
    <?= $form->password('password', 'Votre mot de passe'); ?>
    <?= $form->submit('Se connecter', ['class' => 'btn btn-success btn-block']); ?>
</form>
