<div class="page-header">
    <p class="pull-right">
        <a href="<?= url('admins/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter un administrateur</a>
    </p>
    <h1><i class="fa fa-key"></i> Gestion des administrateurs <small><i class="fa fa-angle-double-right"></i> <?= $title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.php">Panneau de Contrôle</a></li>
    <li><i class="fa fa-key"></i> <a href="<?= url('admins'); ?>">Administrateurs</a></li>
    <li class="active"><?= $title; ?></li>
</ol>

<?php viewFile('partials/errors'); ?>

<form class="form-vertical" action="<?= $url; ?>" method="POST">
    <?= $form->text('name', 'Nom de l\'administrateur'); ?>
    <?= $form->hidden('id', $user->id); ?>
    <?= $form->text('firstname', 'Prénom de l\'administrateur'); ?>
    <?= $form->email('email', 'Email de l\'administrateur'); ?>
    <?= $form->password('password', 'Mot de passe de l\'administrateur'); ?>
    <?= $form->password('password_confirmation', 'Confirmation du mot de passe'); ?>
    <?= $form->submit($title, ['class' => 'btn btn-success btn-block']); ?>
</form>
