<?php
use Core\Helpers\String;
?>

<div class="page-header">
    <h1><i class="fa fa-dashboard"></i> Paneau de Contrôle <small><i class="fa fa-angle-double-right"></i> Statistiques</small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> Panneau de Contrôle</li>
</ol>

<?= viewFile('partials/flash'); ?>

<div class="row">
    <div class="col-md-3">
        <div class="well text-center">
            <h2><i class="fa fa-users fa-2x"></i></h2>
            <p><?= $stats['trainees'] . ' ' . String::plural('étudiant', $stats['trainees']); ?></p>
            <p>
                <a href="<?= url('trainees'); ?>" class="btn btn-primary"><i class="fa fa-list"></i> Liste</a>
                <a href="<?= url('trainees/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
            </p>
        </div>
    </div>

    <div class="col-md-3">
        <div class="well text-center">
            <h2><i class="fa fa-graduation-cap fa-2x"></i></h2>
            <p><?= $stats['formations'] . ' ' . String::plural('formation', $stats['formations']); ?></p>
            <p>
                <a href="<?= url('formations'); ?>" class="btn btn-primary"><i class="fa fa-list"></i> Liste</a>
                <a href="<?= url('formations/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
            </p>
        </div>
    </div>

    <div class="col-md-3">
        <div class="well text-center">
            <h2><i class="fa fa-male fa-2x"></i></h2>
            <p><?= $stats['trainers'] . ' ' . String::plural('formateur', $stats['trainers']); ?></p>
            <p>
                <a href="<?= url('trainers'); ?>" class="btn btn-primary"><i class="fa fa-list"></i> Liste</a>
                <a href="<?= url('trainers/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
            </p>
        </div>
    </div>

    <div class="col-md-3">
        <div class="well text-center">
            <h2><i class="fa fa-building fa-2x"></i></h2>
            <p><?= $stats['companies'] . ' ' . String::plural('entreprise', $stats['companies']); ?></p>
            <p>
                <a href="<?= url('companies'); ?>" class="btn btn-primary"><i class="fa fa-list"></i> Liste</a>
                <a href="<?= url('companies/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <p class="pull-right">
                <a href="<?= url('trainees'); ?>" class="btn btn-sm btn-primary"><i class="fa fa-list"></i> Liste complète</a>
            </p>
            <h2><i class="fa fa-users"></i> Derniers étudiants</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Nom</th>
                    <th class="text-center">Prénom</th>
                    <th class="text-center">Formation</th>
                    <th class="text-center">Ajout</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach( $stats['students'] as $trainee ): ?>
                <tr>
                    <td class="text-center"><img class="img-responsive img-thumbnail" height="40px" width="40px" src="<?= $trainee->photo; ?>" alt=""></td>
                    <td class="text-center"><?= $trainee->name; ?></td>
                    <td class="text-center"><?= $trainee->firstname; ?></td>
                    <td class="text-center"></td>
                    <td class="text-center"><?= \Core\Helpers\Date::ago($trainee->create_date); ?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <div class="well">
            <p class="pull-right">
                <a href="<?= url('internships/create'); ?>" class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Ajouter</a>
                <a href="<?= url('internships'); ?>" class="btn btn-primary btn-sm"><i class="fa fa-list"></i> Liste complète</a>
            </p>
            <h2><i class="fa fa-laptop"></i> Derniers stages</h2>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="text-center">Intitulé</th>
                    <th class="text-center">Entreprise</th>
                    <th class="text-center">Ajout</th>
                    <th class="text-center">Disponible</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach( $stats['internships'] as $internship ): ?>
                <tr>
                    <td class="text-center"><?= $internship->title; ?></td>
                    <td class="text-center"><?= collection('company')->getCompany($internship->company_id); ?></td>
                    <td class="text-center"><?= \Core\Helpers\Date::ago($internship->create_date); ?></td>
                    <td class="text-center"><?= $internship->active ? 'Oui' : 'Non'; ?></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>