        <footer class="container">
            <script src="Design/js/jquery-1.11.3.min.js"></script>
            <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>        
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
            <script src="Design/js/script.js"></script>
            &copy; Copyright
        <script>
        
            $.validate();
            $(function() {  
                
                $( ".datepicker" ).datepicker({
                    dateFormat: "dd/mm/yy",
                    showOn: "both"
                });
                
            });
        </script>
        </footer>
    </body
</html>