<div class="page-header">
    <h1><i class="fa fa-dashboard"></i> Paneau de Contrôle <small><i class="fa fa-angle-double-right"></i> Statistiques</small></h1>
</div>

<?= nav([]); ?>

<div class="row">
    <div class="col-md-3">
        <div class="well text-center">
            <h2><i class="fa fa-male fa-2x"></i></h2>
            <p><?= $stats['trainers'] . ' ' . String::plural('formateur', $stats['trainers']); ?></p>
            <p>
                <a href="index.php?c=trainers" class="btn btn-primary"><i class="fa fa-list"></i> Liste</a>
                <a href="index.php?c=trainers&a=create" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter</a>
            </p>
        </div>
    </div>
</div>
