<?php
if(isset($_SESSION['login'], $_SESSION['profile_id']))
{
	?>
		<h2>Vous ne pouvez pas accéder à cette page</h2>
	<?php
}
else
{
	?>
	<div class="col-md-offset-4 col-md-4">
		<h2>Se connecter</h2>
		<form action="" method="post">
		  	<div class="form-group">
				<label for="email">Adresse email</label>
				<input type="text" class="form-control" name="email" id="firstname" placeholder="Votre adresse email">
			</div>
			<div class="form-group">
				<label for="password">Mot de passe</label>
				<input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe">
			</div>
		  <button type="submit" class="btn btn-success">Se connecter</button>
		</form>
	</div>
	<?php
}