<?php if( response()->getErrors() ): ?>
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4>Des erreurs empêchent la validation du formulaire</h4>
    <ol>
    <?php foreach( response()->getErrors() as $error ): ?>
        <li><?= $error; ?></li>
    <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
