<ul class="nav nav-tabs">
    <li role="presentation"<?= ((uri() == 'formations') ? 'class="active"' : '') ?>>
        <a href="<?= url('formations'); ?>">
            Formations
        </a>
    </li>
    <li role="presentation"<?= ((uri() == 'edit') ? 'class="active"' : '') ?>>
        <a href="<?= url('formations/create'); ?>">
            Ajouter
        </a>
    </li>
    <li role="presentation"<?= ((uri() == 'index') ? 'class="active"' : '') ?>>
        <a href="/index.php?c=formationSession&a=index">
            Sessions de Formation
        </a>
    </li>
    <li role="presentation"<?= ((uri() == 'index') ? 'class="active"' : '') ?>>
        <a href="/index.php?c=matter&a=index">
            Matières
        </a>
    </li>
</ul>
<p>&nbsp;</p>