<ul class="nav nav-tabs">
    <li role="presentation" <?= (uri() === 'edit' ? 'class="active"' : '') ?>>
        <a href="<?= url('trainers/' . $trainer->id .  '/edit'); ?>">
            Modifier le formateur
        </a>
    </li>
    <li role="presentation" <?= (uri() === 'timesheet' ? 'class="active"' : '') ?>>
        <a href="<?= url('trainers/' . $trainer->id .  '/timesheet'); ?>">
            Feuilles de présence & Sessions de formation
        </a>
    </li>
    <li role="presentation" <?= ((uri() === 'matters' || uri() === 'level') ? 'class="active"' : '') ?>>
        <a href="<?= url('trainers/' . $trainer->id .  '/matters'); ?>">
            Niveaux & Compétences
        </a>
    </li>
</ul>
<p>&nbsp;</p>