<div class="page-header">
    <p class="pull-right">
        <a href="<?= url('users/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Enregistrer un administrateur</a>
    </p>
    <h1><i class="fa fa-laptop"></i> Gestion des administrateurs <small><i class="fa fa-angle-double-right"></i> Liste des administrateurs</small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.php">Panneau de Contrôle</a></li>
    <li class="active"><i class="fa fa-users"></i> Administrateurs</li>
</ol>

<?php viewFile('partials.flash'); ?>

<table class="table table-stripped">
    <thead>
    <tr>
        <th class="text-center">

        </th>
    </tr>
    </thead>
</table>
