<div class="page-header">
    <p class="pull-right">
        <a href="<?= App::url('internships/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter un stage</a>
    </p>
    <h1><i class="fa fa-laptot"></i> Gestion des stages <small><i class="fa fa-angle-double-right"></i> <?= $internship->title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="<?= App::url('/'); ?>">Panneau de Contrôle</a></li>
    <li><i class="fa fa-laptop"></i> <a href="<?= App::url('/'); ?>">Gestion des stages</a></li>
    <li class="active"><i class="fa fa-laptop"></i> <?= $internship->title; ?></li>
</ol>
<div class="row">
    <div class="col-md-8">

        <h2>Présentation du stage</h2>
        <ul class="list-inline small">
            <li><i class="fa fa-credit-card"></i> <strong>Rémunéré</strong> : <?= $internship->getWage(); ?></li>
            <?php if( $internship->pay ): ?>
            <li><i class="fa fa-euro"></i> <strong>Rémunération</strong> : <?= $internship->pay; ?> €</li>
            <?php endif; ?>
            <li><i class="fa fa-calendar"></i> <strong>Ajout</strong> : <?= \Core\Helpers\Date::datetime($internship->create_date); ?></li>
            <li><i class="fa fa-clock-o"></i> <strong>Modification</strong> : <?= \Core\Helpers\Date::ago($internship->update_date); ?></li>
        </ul>
        <hr>
        <p class="text-justify">
            <?= $internship->explain; ?>
        </p>
    </div>
    <div class="col-md-4">
        <div class="well well">
            <h2><?= $company->name; ?></h2>
            <ul>
                <li><?= $company->status; ?></li>
                <li><?= $company->address; ?></li>
                <li><?= $company->country; ?></li>
            </ul>
        </div>
    </div>
</div>