
<form id="internshipForm" method="post" action="index.php?c=internship&a=form">

	<div class="form-group">
		<label></label>
		<input class="form-control" name="id" type="hidden" value="<?php if (isset($_GET['id'])) {	echo $_GET['id']; }else{ echo 0; } ?>" />
	</div>

	<div class="form-group">
		<label>Intitulé du stage</label>
		<input class="form-control" name="title" type="text" value="<?= $internship->getData('title');  ?>" />
	</div>

	<div class="form-group">
		<label>Description</label>
		<textarea class="form-control" name="explain"><?= $internship->getData('explain'); ?></textarea>
	</div>

	<div class="form-group">
		<label>Entreprise</label>
		<select name="company_id">
			<?php
			foreach ($companies as $company) {					
			?>
				<option 
					<?php 
					if (isset($_GET['id']) && $_GET['id'] != 0 && $company->getData('id') == $internship->getData('company_id')) {
					?> 
						selected="selected"
					<?php
					} 
					?>
					value="
					<?= 
					$company->getData('id');?>"><?= $company->getData('name');
					?>
				</option>				
			<?php
			}
			?>
		</select>
	</div>

	<div class="form-group">
		<label>Formation</label>
		<input class="form-control" name="formation_id" type="text" value="<?= $internship->getData('formation_id'); ?>" />
	</div>

	<div class="form-group">
		<label>Referent</label>
		<input class="form-control" name="referent_id" type="text" value="<?= $internship->getData('referent_id'); ?>" />
	</div>

	<div class="form-group">
		<label>Salaire éventuel</label>
		<input class="form-control" name="wage" type="text" value="<?= $internship->getData('wage'); ?>" />
	</div>

	<div class="form-group">
		<input class="form-control" name="update_uid" type="hidden" value="<?= strtotime(date('d/m/Y'));?>" />
	</div>

	<button type="submit" class="btn btn-success">Enregistrer les modifications</button>

</form>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
<script type="text/javascript">
	
	$.validate({
		form : '#internshipForm'
	})
	
	
	
</script> 