<table class="col-md-10 col-lg-10">

	<?php

	foreach ($internships as $internship) {

	?>

		<tr class="col-md-10 col-lg-10">
			<td class="col-md-2 col-lg-2"><?= $internship->getData('title'); ?></td>
			<td class="col-md-2 col-lg-2"> <?= $internship->getCompany()->getData('name'); ?></td>
			<!--<td class="col-md-2 col-lg-2"></td>
			<td class="col-md-1 col-lg-1"></td>-->
			<td class="col-md-3 col-lg-3"><a href="">Voir le stage</a></td>
			<td class="col-md-3 col-lg-3"><a href="index.php?c=internship&a=edit&id=<?= $internship->getData('id') ?>">Modifier le stage</a></td>
		</tr>

	<?php

	}

	?>

</table>