<form method="post" action="#">

	<div class="form-group">
		<label></label>
		<input class="form-control" type="hidden" value="" />
	</div>

	<div class="form-group">
		<label>Nom de l'entreprise</label>
		<input class="form-control" type="" value="<?php echo App::getInstance()->getModel('Company')->getData('name');  ?>" />
	</div>

	<div class="form-group">
		<label>Statut</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Nom commercial de l'entreprise</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Adresse</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Code postal</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Ville</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Pays</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Téléphone</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Téléphone 2</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Fax</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Gérant de l'entreprise</label>
		<input class="form-control" type="" value="" />
	</div>

	<button type="submit">Enregistrer les modifications</button>

</form>