
<form id="companyForm" method="post" action="#">

	<div class="form-group">
		<label></label>
		<input class="form-control" type="hidden" value="<?php echo $_GET['id']; ?>" />
	</div>

	<div class="form-group">
		<label>Nom de l'entreprise</label>
		<input class="form-control" type="" value="<?php // echo App::getInstance()->getModel('Company')->getData('name');  ?>" />
	</div>

	<div class="form-group">
		<label>Statut</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Adresse</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Code postal</label>
		<input class="form-control" data-validation="number" type="text" value="" />
	</div>

	<div class="form-group">
		<label>Ville</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Pays</label>
		<input class="form-control" type="" value="" />
	</div>
	
	<!-- !!!!! CHANGEMENT de place ( remplacement de company name) !!!!!! -->
	<div class="form-group">
		<label>E-mail</label>
		<input class="form-control" data-validation="email" type="text" value="" />
	</div>

	<div class="form-group">
		<label>Téléphone</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Téléphone 2</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Fax</label>
		<input class="form-control" type="" value="" />
	</div>

	<div class="form-group">
		<label>Gérant de l'entreprise</label>
		<input class="form-control" type="" value="" />
	</div>

	<button type="submit">Enregistrer les modifications</button>

</form>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
<script type="text/javascript">
	
	$.validate({
		form : '#companyForm'
	})
	
	
	
</script> 