
<form id="companyForm" method="post" action="index.php?c=company&a=form">

	<div class="form-group">
		<label></label>
		<input class="form-control" name="id" type="hidden" value="<?php if (isset($_GET['id'])) {	echo $_GET['id']; }else{ echo 0; } ?>" />
	</div>

	<div class="form-group">
		<label>Nom de l'entreprise</label>
		<input class="form-control" name="name" type="text" value="<?= $company->getData('name');  ?>" />
	</div>

	<div class="form-group">
		<label>Statut</label>
		<input class="form-control" name="status" type="text" value="<?= $company->getData('status'); ?>" />
	</div>

	<div class="form-group">
		<label>Adresse</label>
		<input class="form-control" name="address" type="text" value="<?= $company->getData('address'); ?>" />
	</div>

	<div class="form-group">
		<label>Code postal</label>
		<input class="form-control" data-validation="number" name="postal_code" type="text" value="<?= $company->getData('postal_code'); ?>" />
	</div>

	<div class="form-group">
		<label>Ville</label>
		<input class="form-control" name="city" type="text" value="<?= $company->getData('city'); ?>" />
	</div>

	<div class="form-group">
		<label>Pays</label>
		<input class="form-control" name="country" type="text" value="<?= $company->getData('country'); ?>" />
	</div>

	<div class="form-group">
		<label>E-mail</label>
		<input class="form-control" name="email" data-validation="email" type="email" value="<?= $company->getData('email'); ?>" />
	</div>

	<div class="form-group">
		<label>Téléphone</label>
		<input class="form-control" name="phone" type="text" value="<?= $company->getData('phone'); ?>" />
	</div>

	<div class="form-group">
		<label>Téléphone 2</label>
		<input class="form-control" name="mobile" type="text" value="<?= $company->getData('mobile'); ?>" />
	</div>

	<div class="form-group">
		<label>Fax</label>
		<input class="form-control" name="fax" type="text" value="<?= $company->getData('fax'); ?>" />
	</div>

	<div class="form-group">
		<label>Gérant de l'entreprise</label>
		<input class="form-control" name="manager" type="text" value="<?= $company->getData('manager'); ?>" />
	</div>
	
	<div class="form-group">
		<input class="form-control" name="create_uid" type="hidden" value="0" />
	</div>

	<button type="submit" class="btn btn-success">Enregistrer les modifications</button>

</form>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.2.43/jquery.form-validator.min.js"></script>
<script type="text/javascript">
	
	$.validate({
		form : '#companyForm'
	})
	
	
	
</script> 