<div class="col-md-12, col-lg-12">
	<a class="col-offset-md-8 col-offset-lg-8 col-md-4 col-lg-4 pull-right" href="index.php?c=company&a=edit&id=0">Ajouter une entreprise</a>
</div>

<table class="col-md-12 col-lg-12">

<tr>
	<td class="col-md-2 col-lg-2">Nom</td>
	<td class="col-md-2 col-lg-2">Ville</td>
	<td class="col-md-2 col-lg-2">Pays</td>
	<td class="col-md-2 col-lg-2">Tel.</td>
</tr>

<?php

foreach ($companies as $company) {
?>

	<tr>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('name'); ?></td>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('city'); ?></td>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('country'); ?></td>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('phone'); ?></td>
		<td class="col-md-1 col-lg-1"><a href="index.php?c=company&a=show&id=<?= $company->getData('id') ?>">Voir</a></td>
		<td class="col-md-1 col-lg-1"><a href="index.php?c=company&a=edit&id=<?= $company->getData('id') ?>">Modifier</a></td>
		<td class="col-md-2 col-lg-2"><a href="index.php?c=company&a=delete&id=<?= $company->getData('id') ?>">Supprimer</a></td>
	</tr>

<?php
}
?>

</table>