<a href="index.php?c=company&a=edit&id=0">Ajouter une entreprise</a>

<table class="col-md-10 col-lg-10">

<?php

foreach ($companies as $company) {
?>

	<tr class="col-md-12 col-lg-13">
		<td class="col-md-2 col-lg-2"> <?= $company->getData('name'); ?></td>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('city'); ?></td>
		<td class="col-md-2 col-lg-2"> <?= $company->getData('country'); ?></td>
		<td class="col-md-1 col-lg-1"> <?= $company->getData('phone'); ?></td>
		<td class="col-md-2 col-lg-2"><a href="">Voir l'entreprise</a></td>
		<td class="col-md-2 col-lg-2"><a href="index.php?c=company&a=edit&id=<?= $company->getData('id') ?>">Modifier</a></td>
		<td class="col-md-2 col-lg-2"><a href="index.php?c=company&a=edit&id=<?= $company->getData('id') ?>">Supprimer</a></td>
	</tr>

<?php
}
?>

</table>