<table>
	<tr><td><?= $company->getData('name');?></td></tr>
	<tr><td><?= $company->getData('statuts');?></td></tr>
	<tr><td><?= $company->getData('address');?></td></tr>
	<tr><td><?= $company->getData('postal_code');?></td></tr>
	<tr><td><?= $company->getData('city');?></td></tr>
	<tr><td><?= $company->getData('country');?></td></tr>
	<tr><td><?= $company->getData('email');?></td></tr>
	<tr><td><?= $company->getData('phone');?></td></tr>
	<tr><td><?= $company->getData('mobile');?></td></tr>
	<tr><td><?= $company->getData('fax');?></td></tr>
	<tr><td><?= $company->getData('manager');?></td></tr>
	<tr><td></td></tr>
	<tr><td></td></tr>
</table>

<a href="index.php?c=company&a=index"><i class="fa fa-arrow-left"></i> Retour à la liste</a>