<div class="page-header">
    <h1>Enregistrer une nouvelle entreprise</h1>
</div>

<?php include_once(ROOT . 'App/Views/partials/errors.phtml'); ?>

<form class="form-vertical" method="POST" action="<?= url('companies/create'); ?>">
    <div class="row">
        <div class="col-md-4">
            <?= $form->text('name', 'Nom de l\'entreprise', ['icon' => 'building']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('status', 'Status de l\'entreprise', ['icon' => 'suitcase']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('manager', 'Gérant de l\'entreprise', ['icon' => 'user-secret']); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->text('city', 'Ville de l\'entreprise', ['icon' => 'map-marker']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('country', 'Pays de l\'entreprise', ['icon' => 'compass']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('postal_code', 'Code postal', ['icon' => 'map-signs']); ?>
        </div>
    </div>
    <?= $form->text('address', 'Adresse de l\'entreprise', ['icon' => 'map']); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->text('phone', 'Fixe de l\'entreprise', ['icon' => 'phone']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('mobile', 'Mobile de l\'entreprise', ['icon' => 'mobile']); ?>
        </div>
        <div class="col-md-4">
            <?= $form->text('fax', 'Fax de l\'entreprise', ['icon' => 'fax']); ?>
        </div>
    </div>
    <?= $form->submit('Soumettre le formulaire', ['class' => 'btn btn-block btn-success']); ?>
</form>


