<div class="page-header">
    <p class="pull-right">
        <a href="<?= url('companies/create'); ?>" class="btn btn-success"><i class="fa fa-plus"></i> Ajouter une entreprise</a>
        <a href="#" id="load-toggle" class="btn btn-success"><i class="fa fa-laptot"></i> Charger les entreprises</a>
    </p>
    <h1><i class="fa fa-building-o"></i> Gestion des entreprises <small><i class="fa fa-angle-double-right"></i> Liste des entreprises</small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.phh">Panneau de Contrôle</a></li>
    <li class="active"><i class="fa fa-business"></i> Entreprises</li>
</ol>
<?php viewFile('partials/flash'); ?>

<div id="results">

</div>

