<div class="page-header">
    <p class="pull-right">
        <a href="<?= url('companies/' . $company->id . '/edit'); ?>" class="btn btn-primary"><i class="fa fa-pencil"></i> Modifier</a>
        <a href="<?= url('companies/' . $company->id . '/delete'); ?>" class="btn btn-danger"><i class="fa fa-trash-o"></i> Supprimer</a>
    </p>
    <h1><i class="fa fa-building-o"></i> <?= $company->name; ?> <small><i class="fa fa-angle-double-right"></i> Informations</small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="<?= url('/'); ?>">Panneau de Contrôle</a></li>
    <li><i class="fa building"></i> <a href="<?= url('companies'); ?>">Entreprises</a></li>
    <li class="active"><i class="fa fa-building-o"></i> <?= $company->name; ?></li>
</ol>
<?php viewFile('partials/flash'); ?>

<div class="row">
    <div class="col-md-4">
        <div class="well">
            <h2>Informations</h2>
            <ul class="list-unstyled">
                <li><i class="fa fa-building"></i> <?= $company->status; ?></li>
                <li><i class="fa fa-map-marker"></i> <?= $company->address; ?></li>
            </ul>
        </div>
    </div>
</div>


