<p class="pull-right">
    <a href="<?= url('companies/' . $company->id . '/edit'); ?>" class="btn btn-info">Modifier</a>
    <a href="<?= url('companies/' . $company->id . '/delete'); ?>" class="btn btn-danger">Supprimer</a>
</p>
<h1>Entreprise : <?= $company->name; ?></h1>

<p>Liste des stages</p>

<ul>
    <?php foreach($company->getInternships() as $stage): ?>
        <li><a href="<?= url('internships/' . $stage->id); ?>"><?= $stage->title; ?></a></li>
    <?php endforeach; ?>
</ul>


