<div class="page-header">
    <h1><i class="fa fa-building-o"></i> Gestion des entreprises <small><i class="fa fa-angle-double-right"></i> <?= $title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.php">Panneau de Contrôle</a></li>
    <li><i class="fa fa-building"></i> <a href="/index.php?c=companies">Entreprises</a></li>
    <li class="active"> <?= $title; ?></li>
</ol>

<form class="form-vertical" method="POST" action="" autocomplete="off">
    <div class="row">
        <div class="col-md-6">
            <label>Nom de l'entreprise</label>
            <input type="text" name="name" value="<?= $company->name ?>">
            <input type="hidden" name="id" value="<?= $company->id ;?>">
            <input type="hidden" name="create_date" value="<?= $company->create_date ;?>">
        </div>
        <div class="col-md-6">
            <label>Status de l'entreprise</label>
            <input type="text" name="status" value="<?= $company->status ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <label>Email de contact</label>
            <input type="text" name="email" value="<?= $company->email ?>">
        </div>
        <div class="col-md-4">
            <label>Gérant de l'entreprise</label>
            <input type="text" name="manager" value="<?= $company->manager ?>">
        </div>
        <div class="col-md-4">
            <label>Mobile de contact</label>
            <input type="text" name="mobile" value="<?= $company->mobile ?>">
        </div>
    </div>
            <label>Adresse de l'entreprise</label>
            <input type="text" name="address" value="<?= $company->address ?>">
    <div class="row">
        <div class="col-md-4">
            <label>Ville de l'entreprise</label>
            <input type="text" name="city" value="<?= $company->city ?>">
        </div>

        <div class="col-md-4">
            <label>Code postal</label>
            <input type="text" name="postal_code" value="<?= $company->postal_code ?>">
        </div>

        <div class="col-md-4">
            <label>Pays de l'entreprise</label>
            <input type="text" name="country" value="<?= $company->country ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <label>Fixe de l'entreprise</label>
            <input type="text" name="phone" value="<?= $company->phone ?>">
        </div>

        <div class="col-md-6">
            <label>Fax de l'entreprise</label>
            <input type="text" name="fax" value="<?= $company->fax ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="checkbox">
                <label>
                    <input name="active" type="checkbox" value="1">
                    Stage actif ?
                </label>
            </div>
        </div>
    </div>
    <input type="submit" class="btn btn-block btn-success" value="Soumettre le formulaire">
</form>