<div class="page-header">
    <h1><i class="fa fa-graduation-cap"></i> Gestion des formations <small><i class="fa fa-angle-double-right"></i> <?= $title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.php">Panneau de Contrôle</a></li>
    <li><i class="fa fa-graduation-cap"></i> <a href="<? url('formations'); ?>">Formations</a></li>
    <li class="active"><?= $title; ?></li>
</ol>
<?php viewFile('partials/flash'); ?>

<?php include_once('App/Views/partials/menu-formation.phtml'); ?>

<form method="post" action="" class="form-vertical">
    <input type="hidden" name="id" value="<?= $maFormation->getData('id');?>" />
    <div class="form-group">
        <label>Titre : </label>
        <input type="text" name="title" class="form-control" data-validation-help="Veuillez entrer l'intitulé de la formation" data-validation="length" data-validation-length="max100" data-validation="required" value="<?= $maFormation->getData('title'); ?>" />

    </div>
    <div class="form-group">
        <label>Effectif moyen : </label>
        <input type="text" class="form-control" name="average_effective" data-validation-help="Veuillez entrer l'effectif moyen de la formation" data-validation="number" data-validation-allowing="range[1;99]" data-validation="required"  value="<?= $maFormation->getData('average_effective'); ?>" />
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label>Heures conventionnées en Centre : </label>
                <input type="text" class="form-control" name="convention_hour_center" data-validation-help="Veuillez entrer le nombre d'heures conventionnées en centre" data-validation="number" data-validation-allowing="range[1;9999]" data-validation="required" value="<?= $maFormation->getData('convention_hour_center');?>" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>Heures conventionnées en Entreprise : </label>
                <input type="text" class="form-control" name="convention_hour_company" data-validation-help="Veuillez entrer le nombre d'heures conventionnées en entreprise" data-validation="number" data-validation-allowing="range[1;9999]" data-validation="required" value="<?= $maFormation->getData('convention_hour_company');?>" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Code Marché : </label>
        <input type="text" name="deal_code" class="form-control" data-validation-help="Veuillez entrer le code marché de la formation" data-validation="required" value="<?= $maFormation->getData('deal_code');?>" />
    </div>
    <label>Matières: </label>
    <select multiple class="form-control col-md-2" data-validation="required" name="matters[]">
        <?php
        //faire une boucle qui va, pour chaque itération, afficher le contenu du n-ième objet
        foreach($coll_matter as $matter)
        {
            ?>
            <option value="<?= $matter->getData('id'); ?>" <?php echo (in_array($matter, $maFormation->getMatters()) ? 'selected' : ''); ?>><?= $matter->getData('title'); ?></option>
            <?php
        }
        ?>
    </select>
    <div class="form-group">
        <label>Donneur d'ordre : </label>
        <input class="form-control" type="text" name="order_giver" data-validation-help="Veuillez entrer le donneur d'ordre de la formation" data-validation="required" value="<?= $maFormation->getData('order_giver');?>" />
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label>Date de début : </label>
                <input type="text" class="datepicker form-control" data-validation-format="dd/mm/yyyy" data-validation="required" name="deal_begin_date" value="<?= $maFormation->getData('deal_begin_date');?>" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>Date de fin : </label>
                <input type="text" class="datepicker form-control" data-validation-format="dd/mm/yyyy" data-validation="required" name="deal_ending_date" value="<?= $maFormation->getData('deal_ending_date');?>" />

            </div>
        </div>
    </div>
    <div class="form-group">
        <button name="submit" class="btn btn-success btn-block"><?= $title; ?></button>
    </div>
</form>