<div class="page-header">
    <h1><i class="fa fa-building-o"></i> Gestion des stages <small><i class="fa fa-angle-double-right"></i> <?= $title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="index.php">Panneau de Contrôle</a></li>
    <li><i class="fa fa-laptop"></i> <a href="<?= url('companies'); ?>">Stages</a></li>
    <li class="active"> <?= $title; ?></li>
</ol>

<?php viewFile('partials.errors'); ?>

<form class="form-vertical" action="<?= $url; ?>" method="POST">
    <div class="form-group">
        <?= $form->text('title', 'Intitulé du stage'); ?>
        <?= $form->textarea('explain', 'Description du stage', ['rows' => '5']); ?>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $form->select('company_id', 'Entreprise proposant le stage', $companies); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <?= $form->select('formation_id', 'Formation en rapport avec le stage', $formations, 'title'); ?>
            </div>
        </div>
    </div>
</form>
