<table class="table" id="matters-levels">
	<tr>
		<td>Matière</td>
		<td>Note</td>
		<td>Appréciation</td>
		<td></td>
	</tr>
	<?php
	if($trainer->getLevels())
	{
		foreach($trainer->getLevels() as $level)
		{ 
			?>
				<tr>
					<td><?php echo $level->getMatter()->getData('title'); ?></td>
					<td><?php echo $level->getData('note'); ?></td>
					<td><?php echo $level->getData('appreciation'); ?></td>
					<td>
						<a class="btn btn-primary edit-level" data-id="<?php echo $level->id; ?>" href="#">Editer</a>
					</td>
					<td>
						<form method="post">
							<input type="hidden" name="level" value="<?php echo $level->getData('id'); ?>">
							<input type="hidden" name="delete" value="1">
							<input type="submit" class="btn btn-danger" value="Supprimer">
						</form>
					</td>
				</tr>
			<?php
		}			
	}
	?>
</table>