<div  class="col-md-12 list-matter">
    <div  class="col-md-12">
        <a class="select-matter" formation="<?= $id_formation; ?>" href="#"><h3>Ajouter une réfèrence pédagogique</h3></a>
        <div class="selected-matter-<?= $id_formation; ?>"></div>
    </div>
    
    <?php
        //faire une boucle qui va, pour chaque itération, afficher le contenu du n-ième objet
        foreach ($coll_refpedago as $refpedago){ 
                  
    ?>                      
    <div class="refPedago-<?= $refpedago->getData('id'); ?>">
        <div class="col-md-6">
            <?php  echo $refpedago->getMatter()->getData('title'); ?>
        </div>
        <div class="col-md-6">                  
            <a class="deleteRefPedago" href="#" formation="<?= $refpedago->getData('formations_id'); ?>" refpedago="<?= $refpedago->getData('id'); ?>">Supprimer cette réfèrence pedagogique</a>
        </div>        
    </div>
    <?php   
        }  
    ?>
</div>