<div class ="col-md-3">
    <form method="post" action="#" class="post-add-matter">
        <input type="hidden" name="formation" value="<?= $id_formation; ?>">
        <select name="matter" class="form-control">
<?php
    foreach($coll_matter as $matter)
    {
    	?>
            <option value="<?= $matter->getData('id'); ?>"><?= $matter->getData('title'); ?></option>
    	<?php
    }
?>
        </select>
        <button name="submit">Ajouter cette matière</button>
    </form>
</div>