<div class="panel panel-primary">
    <div class="panel-heading">
        <?php echo $formation->title; ?> Gestion des matières
    </div>
    <div class="panel-body">
        <table class="table table-striped list-matter">
            <tr>
                <td>Nom matière</td>
                <td></td>
            </tr>
            <?php
                //faire une boucle qui va, pour chaque itération, afficher le contenu du n-ième objet
                foreach($coll_refpedago as $refpedago)
                {
                    ?>
                    <tr class="refPedago-<?= $refpedago->getData('id'); ?> matter-<?= $refpedago->getMatter()->id ?>">
                        <td>
                            <?php  echo $refpedago->getMatter()->getData('title'); ?>
                        </td>
                        <td class="deleteRefPedago" refpedago="<?= $refpedago->getData('id'); ?>">
                            <a class="btn btn-danger" href="#">Supprimer cette matière de la formation</a>
                        </td>
                    </tr>
                  <?php
                }
            ?>
        </table>
        <div class="selected-matter"></div>
        <a class="select-matter btn btn-success" formation="<?= $id_formation; ?>" href="#">
            Ajouter une matière à la formation
        </a>
    </div>
</div>