<div  class="col-md-12 list-matter">
        <div  class="col-md-12 list-matter">
            <a class="select-matter" href="#"><h3>Ajouter une réfèrence pédagogique</h3></a>
            <div class="selected-matter"></div>
        </div>
        <?php
            //faire une boucle qui va, pour chaque itération, afficher le contenu du n-ième objet
            for ($i=0; $i < count($coll_refpedago); $i++):                
        ?>                      
                <div class="col-md-6">
                    <?php  echo $coll_refpedago[$i]->getMatter()->getData('title'); ?>
                </div>
                <div class="col-md-6">                  
                    <a href="index.php?c=Ajax&a=deleteRefPedago&id=<?= $coll_refpedago[$i]->getData('id'); ?>">Supprimer cette réfèrence pedagogique</a>
                </div>        
        <?php   
            endfor;
        ?>

</div>