<div class="page-header">
    <h1><i class="fa fa-male"></i> Gestion des formateurs <small><i class="fa fa-angle-double-right"></i>  <?= $title; ?></small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="<?=url('/'); ?>">Panneau de Contrôle</a></li>
    <li><i class="fa fa-male"></i> <a href="<?= url('trainers'); ?>">Formateurs</a></li>
    <li class="active"> <?= $title; ?></li>
</ol>

<?php viewFile('partials.errors'); ?>

<?php if( $trainer->id != 0 ): ?>
<?php include_once('App/Views/partials/menu-trainer.phtml') ?>
<?php endif; ?>

<form class="form-vertical" method="POST" action="<?= $url; ?>" enctype="multipart/form-data">
    <h3><strong>Civilité</h3></strong>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="firstname">Prénom</label>
                <input data-validation="length" data-validation-length="min2" class="form-control" type="text" name="firstname" value="<?php echo $trainer->getData('firstname'); ?>" id="firstname">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="name">Nom</label>
                <input data-validation="length" data-validation-length="min2" class="form-control" type="text" name="name" value="<?php echo $trainer->getData('name'); ?>" id="name">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div>
                <label>Genre</label>
            </div>
            <div class="btn-group" id="genders" data-toggle="buttons">
                <label class="btn btn-default <?php echo $trainer->getData('gender') == 'male' ? 'active':''; ?>" for="radio1">
                    Homme
                    <input id="radio1" type="radio" name="gender" <?php echo $trainer->getData('gender') == 'male' ? 'checked':''; ?> value="male" required />
                </label>

                <label class="btn btn-default <?php echo $trainer->getData('gender') == 'female' ? 'active': ''; ?>" for="radio2">
                    Femme
                    <input id="radio2" type="radio" name="gender" <?php echo $trainer->getData('gender') == 'female' ? 'checked': ''; ?> value="female" required />
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="family_status_id">Statut familial</label>
                <select class="form-control" name="family_status_id" id="family_status_id">
                    <?php
                    foreach($familyStatuss as $familyStatus)
                    {
                        ?>
                        <option value="<?php echo $familyStatus->getData('id'); ?>" <?php echo $familyStatus->getData('id') == $trainer->getData('family_status_id') ? 'selected' : '';?>><?php echo $familyStatus->getData('title'); ?></option>

                        <?php
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="birthday">Date de naissance</label>
                <input data-validation="date" data-validation-format="dd/mm/yyyy" class="form-control datepicker" type="text" name="birthday" value="<?php echo date('d/m/Y', strtotime($trainer->getData('birthday'))); ?>" id="birthday">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="nationality_id">Nationalité</label>
                <select class="form-control" name="nationality_id" id="nationality_id">
                    <?php
                    foreach($nationalities as $nationality)
                    {
                        ?>
                        <option value="<?php echo $nationality->getData('id'); ?>" <?php echo $trainer->getData('nationality_id') == $nationality->getData('id') ? 'selected': ''; ?>><?php echo $nationality->getData('title'); ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="birthdayplace">Lieu de naissance</label>
                <input class="form-control" type="text" name="birthdayplace" value="<?php echo $trainer->getData('birthdayplace'); ?>" id="birthdayplace" data-validation="required">
            </div>
        </div>
    </div>
    <h3><strong>Adresse officielle</h3></strong>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_off_street">Rue</label>
                <input class="form-control" type="text" name="address_off_street" value="<?php echo $trainer->getData('address_off_street'); ?>" id="address_off_street" data-validation="required">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_off_complement">Complément</label>
                <input class="form-control" type="text" name="address_off_complement" value="<?php echo $trainer->getData('address_off_complement'); ?>" id="address_off_complement">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_off_codpost">Code postal</label>
                <input class="form-control" type="number" name="address_off_codpost" value="<?php echo $trainer->getData('address_off_codpost'); ?>" id="address_off_codpost" data-validation="length" data-validation="number" data-validation-length="5">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_off_city">Ville</label>
                <input class="form-control" type="text" name="address_off_city" value="<?php echo $trainer->getData('address_off_city'); ?>" id="address_off_city" data-validation="required">
            </div>
        </div>
    </div>
    <h3><strong>Lieu de vie (optionnel)</h3></strong>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_form_street">Rue</label>
                <input class="form-control" type="text" name="address_form_street" value="<?php echo $trainer->getData('address_form_street'); ?>" id="address_form_street">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_form_complement">Complement</label>
                <input class="form-control" type="text" name="address_form_complement" value="<?php echo $trainer->getData('address_form_complement'); ?>" id="address_form_complement">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_form_codpost">Code postal</label>
                <input class="form-control" type="text" name="address_form_codpost" value="<?php echo $trainer->getData('address_form_codpost'); ?>" id="address_form_codpost" data-validation-optional="true" data-validation="length" data-validation="number" data-validation-length="5">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="address_form_city">Ville</label>
                <input class="form-control" type="text" name="address_form_city" value="<?php echo $trainer->getData('address_form_city'); ?>" id="address_form_city">
            </div>
        </div>
    </div>
    <h3><strong>Informations supplémentaires</h3></strong>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="mail">Email</label>
                <input data-validation="email" class="form-control" type="email" name="mail" value="<?php echo $trainer->getData('mail'); ?>" id="mail">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="cellphone">Téléphone portable</label>
                <input class="form-control" type="tel" name="cellphone" value="<?php echo $trainer->getData('cellphone'); ?>" id="cellphone">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="phone">Téléphone fixe</label>
                <input class="form-control" type="tel" name="phone" value="<?php echo $trainer->getData('phone'); ?>" id="phone">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="social_security_number">Numéro de sécurité social</label>
                <input class="form-control" type="number" name="social_security_number" value="<?php echo $trainer->getData('social_security_number'); ?>" id="social_security_number" data-validation="length" data-validation="number" data-validation-length="15">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label for="photo">Photo</label>
                <input class="form-control" type="file" name="photo" value="<?php echo $trainer->getData('photo'); ?>" id="photo">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="study_levels_id">Niveau d'étude</label>
                <select class="form-control" name="study_levels_id" id="study_levels_id">

                    <?php
                    foreach ($studyLevels as $studyLevel) {
                        ?>
                        <option value="<?php echo $studyLevel->getData('id') ?>" <?php echo $studyLevel->getData('id') == $trainer->getData('study_levels_id') ? 'selected' : ''; ?>>
                            <?php echo $studyLevel->getData('title'); ?>
                        </option>

                        <?php
                    }
                    ?>


                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="trainer_extern">Formateur externe ?</label>
                <input type="hidden" value="0" name="trainer_extern">
                <input class="form-control" type="checkbox" name="trainer_extern" id="trainer_extern" value="true" <?php if($trainer->getData('trainer_extern')) echo 'checked'; ?> >
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label for="hourly_rate">Taux horaire</label>
                <input class="form-control" type="text" name="hourly_rate" id="hourly_rate" value="<?php echo $trainer->getData('hourly_rate'); ?>">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="further_informations">Plus d'information</label>
                <textarea class="form-control" name="further_informations" value="<?php echo $trainer->getData('further_informations'); ?>" id="further_informations"></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <input type="hidden" name="id" value="<?= $id; ?>" id="id">
        <div class="col-md-3"></div>
        <div class="col-md-3">
            <input class="form-control btn-success" type="submit" value="Enregistrer" id="submit">
        </div>
        <div class="col-md-3">
            <input class="form-control btn-danger" type="reset" name="reset" value="Reset" id="reset">
        </div>
        <div class="col-md-3"></div>
    </div>
</form>