<div class="page-header">
    <h1><i class="fa fa-male"></i> Gestion des formateurs <small><i class="fa fa-angle-double-right"></i>  Session de formations</small></h1>
</div>
<ol class="breadcrumb">
    <li><i class="fa fa-dashboard"></i> <a href="<?=url('/'); ?>">Panneau de Contrôle</a></li>
    <li><i class="fa fa-male"></i> <a href="<?= url('trainers'); ?>">Formateurs</a></li>
    <li><i class="fa fa-male"></i> <a href="<?= url('trainers/' . $trainer->id); ?>"><?= $trainer->getFullName(); ?></a></li>
    <li class="active"> Sessions de formations</li>
</ol>

<?php viewFile('partials.errors'); ?>

<?php if( $trainer->id != 0 ): ?>
    <?php include_once('App/Views/partials/menu-trainer.phtml') ?>
<?php endif; ?>

<table class="table table-striped table-bordered">
    <tr>
        <th>Session de Formation</th>
        <th class="text-center">Mois</th>
        <th class="text-center">Année</th>
        <th class="text-center">Total heures</th>
    </tr>
    <?php
    if($trainer->getTimesheets())
    {
        foreach($trainer->getTimesheets() as $timesheet)
        {
            ?>
            <tr>
                <td>
                    <?php echo $timesheet->getFormationSession()->getFormation()->getData('title').' du '.date('d/m/y', strtotime($timesheet->getFormationSession()->getData('begin_date'))).' au '.date('d/m/y', strtotime($timesheet->getFormationSession()->getData('ending_date'))); ?>
                </td>
                <td><?php echo strftime("%B", strtotime(date('F', mktime(0, 0, 0, $timesheet->getData('month'), 10)))); ?></td>
                <td><?php echo $timesheet->getData('year'); ?></td>
                <td><?php echo $timesheet->getData('total_hours'); ?></td>
                <td>
                    <form method="post">
                        <input type="hidden" name="timesheet_id" value="<?php echo $timesheet->getData('id'); ?>">
                        <input type="hidden" name="delete" value="1">
                        <input type="submit" value="Supprimer" class="btn btn-danger">
                    </form>
                </td>
            </tr>
            <?php
        }
    }
    ?>
</table>
<h2>Ajouter feuille de présence</h2>

<form method="post" action="#" enctype="multipart/form-data" class="form-horizontal">
    <div class="form-group">
        <label for="month" class="col-sm-2 control-label">Mois</label>
        <div class="col-sm-10">
            <select name="month" id="month" class="form-control">
                <option value="1">Janvier</option>
                <option value="2">Février</option>
                <option value="3">Mars</option>
                <option value="4">Avril</option>
                <option value="5">Mai</option>
                <option value="6">Juin</option>
                <option value="7">Juillet</option>
                <option value="8">Août</option>
                <option value="9">Septembre</option>
                <option value="10">Octobre</option>
                <option value="11">Novembre</option>
                <option value="12">Décembre</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="year" class="col-sm-2 control-label">Année</label>
        <div class="col-sm-10">
            <select name="year" id="year" class="form-control">
                <?php
                for ($y=2000; $y <= 2100; $y++)
                {
                    if (date("Y") == $y)
                    {
                        ?><option value="<?php echo $y ?>" selected><?php echo $y; ?></option><?php
                    }
                    else
                    {
                        ?><option value="<?php echo $y ?>"><?php echo $y; ?></option><?php
                    }
                }
                ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="total_hours" class="col-sm-2 control-label">Total heures</label>
        <div class="col-sm-10">
            <input type="text" name="total_hours" id="total_hours" data-validation="number" data-validation="required" class="form-control">
        </div>
    </div>

    <div class="form-group">
        <label for="formation_session" class="col-sm-2 control-label">Session de formation</label>
        <div class="col-sm-10">
            <select name="formation_session_id" id="formation_session" class="form-control">
                <?php
                foreach($formationSessions as $formationSession)
                {
                    ?>
                    <option value="<?php echo $formationSession->getData('id') ?>">
                        <?php
                        echo $formationSession->getFormation()->getData('title').' du '.date('d/m/y', strtotime($formationSession->getData('begin_date'))).' au '.date('d/m/y', strtotime($formationSession->getData('ending_date')));
                        ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </div>
    <input type="submit" value="Ajouter" class="btn btn-success col-md-offset-2 col-md-10">

</form>