<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GestForm</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/cosmo/bootstrap.min.css

">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="./Design/css/main.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php"><i class="fa fa-keyboard-o"></i> Gestion des Formations</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="index.php"><i class="fa fa-home"></i> Accueil</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('trainees'); ?>"><i class="fa fa-users"></i> Etudiants</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('formations'); ?>"><i class="fa fa-graduation-cap"></i> Formations</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('companies'); ?>"><i class="fa fa-male"></i> Formateurs</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('companies'); ?>"><i class="fa fa-building-o"></i> Entreprises</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('internships'); ?>"><i class="fa fa-laptop"></i> Stages</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i> Administrateur	<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-wrench"></i> Mes paramètres</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="container" style="padding-top: 70px;">
    <?= $content; ?>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="./Design/js/form-validator/jquery.form-validator.min.js"></script>
<script src="./Design/js/form-validator/lang/fr.js"></script>
<script src="./Design/js/form-validator/location.js"></script>
<script>
    $.validate({
        lang: 'fr',
        modules: 'location',
        onModulesLoaded: function() {
            $('input[name="country"]').suggestCountry();
        }
    });
</script>
</body>
</html>
