<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GestForm</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/cosmo/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="./Design/css/main.css">

    <script>(function(w,d,u){w.readyQ=[];w.bindReadyQ=[];function p(x,y){if(x=="ready"){w.bindReadyQ.push(y);}else{w.readyQ.push(x);}};var a={ready:p,bind:p};w.$=w.jQuery=function(f){if(f===d||f===u){return a}else{p(f)}}})(window,document)</script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php"><i class="fa fa-keyboard-o"></i> Gestion des Formations</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="index.php"><i class="fa fa-home"></i> Accueil</a></li>
                <?php if( auth()->check()): ?>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('config'); ?>"><i class="fa fa-tachometer"></i> Configuration</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('admins'); ?>"><i class="fa fa-key"></i> Administrateurs</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('trainees'); ?>"><i class="fa fa-users"></i> Etudiants</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('formations'); ?>"><i class="fa fa-graduation-cap"></i> Formations</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('trainers'); ?>"><i class="fa fa-male"></i> Formateurs</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('companies'); ?>"><i class="fa fa-building-o"></i> Entreprises</a></li>
                <li class="divider-vertical"></li>
                <li><a href="<?= url('internships'); ?>"><i class="fa fa-laptop"></i> Stages</a></li>
                <li class="divider-vertical"></li>
                <?php endif; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if( auth()->check() ): ?>
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user"></i> <?= auth()->get('username'); ?> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= url('profile'); ?>"><i class="fa fa-wrench"></i> Mes paramètres</a></li>
                        <li class="divider"></li>
                        <li><a href="<?= url('logout'); ?>"><i class="fa fa-sign-out"></i> Déconnexion</a></li>
                    </ul>
                </li>
                <?php else: ?>
                <li><a href="<?= url('login'); ?>"><i class="fa fa-sign-in"></i> Se connecter</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>

<div class="container" style="padding-top: 70px; padding-bottom:50px;">
    <?= $content; ?>
    <div class="modal fade" id="globalModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title text-center" id="myModalLabel"></h4>
                </div>
                <div class="modal-body"></div>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="text-center"><i class="fa fa-code"></i> avec <i class="fa fa-heart text-danger"></i> par la formation Développeur Web 2015</p>
    </div>
</footer>

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>(function($,d){$.each(readyQ,function(i,f){$(f)});$.each(bindReadyQ,function(i,f){$(d).bind("ready",f)})})(jQuery,document)</script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="./Design/js/ajax-config.js"></script>
<script src="./Design/js/jquery-autocomplete.min.js"></script>

<script src="./Design/js/form-validator/jquery.form-validator.min.js"></script>
<script src="./Design/js/form-validator/lang/fr.js"></script>
<script src="./Design/js/form-validator/location.js"></script>

<script>
    $.validate({
        lang: 'fr'
    });
    $('.datepicker').datepicker({
        dateFormat: "dd/mm/yy",
        gotoCurrent: true,
        changeYear: true,
        dayNames: [ "Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi" ],
        monthNames: [ "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" ],
        dayNamesMin: [ "Di", "Lu", "Ma", "Me", "Je", "Ve", "Sa" ],


    });
</script>
</body>
</html>
